Repository streamchaser/streamchaser, pull requests merged in 2021-11, with the labels that each got.

#82 Sessionstore now works for genres and multiselects load quicker
  frontend/src/routes/index.svelte
  frontend/src/utils.ts
Labels: bug :bug:, prio:medium :construction_worker_man:

#86 Console log mulitiselect spam
  frontend/src/routes/index.svelte
Labels: bug :bug:, prio:low :zzz:

#87 Firefox dynamic import loads error page
  frontend/src/routes/__error.svelte
Labels: bug :bug:, prio:low :zzz:

#2 Add cookie disclaimer
  frontend/src/components/cookie_disclaimer.svelte
  frontend/src/routes/__error.svelte
  frontend/src/routes/about.svelte
  frontend/src/routes/faq.svelte
  frontend/src/routes/index.svelte
  frontend/src/routes/movie/[id].svelte
  frontend/src/routes/person/[id].svelte
  frontend/src/routes/tv/[id].svelte
  frontend/src/stores/cookie_disclaimer.js
Labels: enhancement :unicorn:, prio:high :warning:

#88 + number providers doesnt work
  frontend/src/routes/index.svelte
Labels: bug :bug:, prio:low :zzz:

#84 Add print statements for meilisearch indexing
  backend/app/cli.py
  backend/app/db/database_service.py
Labels: enhancement :unicorn:, prio:low :zzz:

#16 Multiselects gap issues & styling issues
  frontend/src/routes/index.svelte
Labels: bug :bug:, prio:low :zzz:

#89 Genre & providers shown in no results on index page
  frontend/src/components/no_results.svelte
  frontend/src/routes/index.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#99 Fix recommendations breaking previous page
  frontend/src/utils.ts
Labels: bug :bug:, prio:low :zzz:

#100 Duplicate tv and moves in person details-view
  frontend/src/routes/person/[id].svelte
  frontend/src/utils.ts
Labels: bug :bug:, prio:low :zzz:

#91 Handle long descriptions in detailsview
  frontend/src/components/read_more.svelte
  frontend/src/routes/movie/[id].svelte
  frontend/src/routes/person/[id].svelte
  frontend/src/routes/tv/[id].svelte
Labels: enhancement :unicorn:, good first issue, prio:low :zzz:

#26 The frontend pages should make use of components
  frontend/src/components/details/person.svelte
  frontend/src/components/details/person_media.svelte
  frontend/src/components/details/read_more.svelte
  frontend/src/components/details/recommendations.svelte
  frontend/src/components/details/seasons.svelte
  frontend/src/components/details/top_card.svelte
  frontend/src/components/media_search.svelte
  frontend/src/routes/__error.svelte
  frontend/src/routes/index.svelte
  frontend/src/routes/movie/[id].svelte
  frontend/src/routes/person/[id].svelte
  frontend/src/routes/tv/[id].svelte
Labels: enhancement :unicorn:, prio:medium :construction_worker_man:

#102 Add spinner for loading details view & fix recommendations for tv
  frontend/src/components/details/recommendations.svelte
  frontend/src/components/loading/spinner.svelte
  frontend/src/routes/movie/[id].svelte
  frontend/src/routes/person/[id].svelte
  frontend/src/routes/tv/[id].svelte
Labels: enhancement :unicorn:

#92 Better handling of card in detailsview
  frontend/src/components/details/read_more.svelte
  frontend/src/components/details/top_card.svelte
  frontend/src/components/error.svelte
  frontend/src/components/footer.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#104 No results pop up on page launch
  frontend/src/components/media_search.svelte
Labels: bug :bug:, prio:low :zzz:

#6 Write "No providers" when no providers on detail views
  frontend/src/components/details/top_card.svelte
Labels: enhancement :unicorn:, prio:low :zzz:
