Repository streamchaser/streamchaser, pull requests merged in 2022-09, with the labels that each got.

#287 Up'ed svelte-persistent-store to newest version as well as making the…
  frontend/package.json
  frontend/playwright.config.ts
  frontend/src/routes/+error.svelte
  frontend/src/routes/+layout.svelte
  frontend/src/routes/+page.svelte
  frontend/src/routes/about/+page.svelte
  frontend/src/routes/faq/+page.svelte
  frontend/src/routes/movie/[id]/+page.svelte
  frontend/src/routes/person/[id]/+page.svelte
  frontend/src/routes/tv/[id]/+page.svelte
  frontend/src/stores/cookie_disclaimer.js
  frontend/src/stores/country.js
  frontend/src/stores/filters.js
  frontend/src/stores/genres.js
  frontend/src/stores/input.js
  frontend/src/stores/providers.js
  frontend/src/stores/theme.js
  frontend/tsconfig.json
  frontend/vite.config.js
  frontend/yarn.lock
Labels: enhancement :unicorn:, -prio:1 :warning:

#290 move all non-route content into lib/
  frontend/src/lib/components/avatar.svelte
  frontend/src/lib/components/back_to_top_button.svelte
  frontend/src/lib/components/collapse.svelte
  frontend/src/lib/components/cookie_disclaimer.svelte
  frontend/src/lib/components/country_locator.svelte
  frontend/src/lib/components/country_selector.svelte
  frontend/src/lib/components/details/person.svelte
  frontend/src/lib/components/details/person_media.svelte
  frontend/src/lib/components/details/read_more.svelte
  frontend/src/lib/components/details/recommendations.svelte
  frontend/src/lib/components/details/seasons.svelte
  frontend/src/lib/components/details/top_card.svelte
  frontend/src/lib/components/error.svelte
  frontend/src/lib/components/error_buttons.svelte
  frontend/src/lib/components/filters.svelte
  frontend/src/lib/components/footer.svelte
  frontend/src/lib/components/loading/spinner.svelte
  frontend/src/lib/components/media_search.svelte
  frontend/src/lib/components/navbar/navbar.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
  frontend/src/lib/components/no_results.svelte
  frontend/src/lib/components/theme_selector.svelte
  frontend/src/lib/stores/cookie_disclaimer.js
  frontend/src/lib/stores/country.js
  frontend/src/lib/stores/filters.js
  frontend/src/lib/stores/genres.js
  frontend/src/lib/stores/input.js
  frontend/src/lib/stores/providers.js
  frontend/src/lib/stores/theme.js
  frontend/src/lib/types.ts
  frontend/src/lib/utils.ts
  frontend/src/lib/variables.js
  frontend/src/routes/+error.svelte
  frontend/src/routes/+layout.svelte
  frontend/src/routes/+page.svelte
  frontend/src/routes/about/+page.svelte
  frontend/src/routes/faq/+page.svelte
  frontend/src/routes/movie/[id]/+page.svelte
  frontend/src/routes/person/[id]/+page.svelte
  frontend/src/routes/tv/[id]/+page.svelte
Labels: maintenance :safety_vest:

#289 feat: add cached image proxy for posters
  backend/app/db/cache.py
  backend/app/main.py
  backend/app/routers/image.py
  backend/poetry.lock
  backend/pyproject.toml
  frontend/src/lib/variables.js
Labels: bug :bug:, -prio:1 :warning:
