Repository streamchaser/streamchaser, pull requests merged in 2022-03, with the labels that each got.

#54 Rethink amount of elements on rows in index page
  frontend/package.json
  frontend/src/components/details/person.svelte
  frontend/src/components/details/person_media.svelte
  frontend/src/components/media_search.svelte
  frontend/src/routes/index.svelte
  frontend/src/routes/person/[id].svelte
  frontend/src/types.ts
  frontend/src/utils.ts
  frontend/yarn.lock
Labels: enhancement :unicorn:, prio:medium :construction_worker_man:

#177 Filter adult content on person details
  frontend/src/routes/person/[id].svelte
  frontend/src/types.ts
Labels: enhancement :unicorn:, prio:high :warning:

#170 Meilisearch data is not persistent
  docker-compose.yml
Labels: bug :bug:, prio:low :zzz:

#178 Add fade transitions
  backend/blacklist.txt
  frontend/src/components/back_to_top_button.svelte
  frontend/src/components/details/person_media.svelte
  frontend/src/components/media_search.svelte
  frontend/src/components/no_results.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#169 No logs over API calls in production
  backend/Dockerfile
Labels: bug :bug:, prio:medium :construction_worker_man:

#180 Fade out transition delays page loading
  frontend/src/components/media_search.svelte
  frontend/src/components/no_results.svelte
Labels: bug :bug:, prio:low :zzz:

#179 Fix text colours in multi-selects
  frontend/Dockerfile
  frontend/package.json
  frontend/src/components/back_to_top_button.svelte
  frontend/src/components/media_search.svelte
  frontend/src/components/navbar.svelte
  frontend/src/routes/index.svelte
  frontend/tailwind.config.cjs
  frontend/yarn.lock
Labels: bug :bug:, -prio:3 :zzz:

#184 Change genres to use normal aioredis and be in one key
  backend/app/db/cache.py
  backend/app/db/database_service.py
  backend/app/routers/genres.py
  backend/pyproject.toml
  backend/tests/test_cache.py
Labels: enhancement :unicorn:, -prio:3 :zzz:

#188 Filter more untagged TV shows
  backend/blacklist.txt
Labels: -prio:1 :warning:, maintenance :safety_vest:

#185 Move providers to aioredis
  backend/app/db/database_service.py
  backend/app/routers/movie.py
  backend/app/routers/providers.py
  backend/app/routers/tv.py
  backend/cli.py
Labels: enhancement :unicorn:, -prio:3 :zzz:

#187 Replace sync client with meilisearch-python-async for our search endpoint
  backend/app/db/search.py
  backend/app/routers/search.py
  backend/poetry.lock
  backend/pyproject.toml
Labels: enhancement :unicorn:, -prio:3 :zzz:

#148 Setup frontend for serverless
  backend/app/main.py
  frontend/package.json
  frontend/svelte.config.js
  frontend/yarn.lock
Labels: enhancement :unicorn:, -prio:3 :zzz:

#193 Remove/simplify Meilisearch index batching
  backend/app/db/database_service.py
  backend/cli.py
  docker-compose.yml
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#27 The error handling site should route back to the index page, if the user is linked to a dead link from an external source
  frontend/src/components/error.svelte
  frontend/src/components/error_buttons.svelte
  frontend/src/components/loading/spinner.svelte
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#191 Make recommendations scrollable by replacing carousel with swiper-component
  frontend/package.json
  frontend/src/components/cookie_disclaimer.svelte
  frontend/src/components/details/recommendations.svelte
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#196 Setup local Grafana, node_exporter, cAdvisor, Prometheus
  .github/workflows/main.yml
  docker-compose.yml
  prometheus.yml
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#200 Setup CORS to accept the main Vercel URL
  backend/app/main.py
Labels: bug :bug:, -prio:1 :warning:

#198 Rewrite genre fetching from Rust to Go
  .gitignore
  docker-compose.yml
  frontend/src/routes/index.svelte
  frontend/src/variables.js
  go_backend/Dockerfile
  go_backend/go.mod
  go_backend/go.sum
  go_backend/main.go
  go_backend/routes.go
  rust_backend/.dockerignore
  rust_backend/Cargo.lock
  rust_backend/Cargo.toml
  rust_backend/Dockerfile
  rust_backend/src/main.rs
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:
