Repository streamchaser/streamchaser, pull requests merged in 2022-11, with the labels that each got.

#307 make httpx use http2
  backend/app/api.py
  backend/app/routers/country.py
  backend/app/routers/image.py
  backend/cli.py
  backend/pyproject.toml
Labels: enhancement :unicorn:

#292 feat: setup openapi-typescript-codegen
  backend/app/routers/media.py
  backend/app/routers/movie.py
  backend/app/routers/person.py
  backend/app/routers/providers.py
  backend/app/routers/tv.py
  frontend/package.json
  frontend/src/lib/generated/index.ts
  frontend/src/lib/generated/models/Genre.ts
  frontend/src/lib/generated/models/HTTPValidationError.ts
  frontend/src/lib/generated/models/Media.ts
  frontend/src/lib/generated/models/Movie.ts
  frontend/src/lib/generated/models/Person.ts
  frontend/src/lib/generated/models/TV.ts
  frontend/src/lib/generated/models/ValidationError.ts
  frontend/yarn.lock
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#293 refactor: move detail page fetching into load
  backend/app/schemas.py
  frontend/src/lib/components/details/person.svelte
  frontend/src/lib/components/details/person_media.svelte
  frontend/src/lib/components/details/recommendations.svelte
  frontend/src/lib/components/details/top_card.svelte
  frontend/src/lib/generated/models/Movie.ts
  frontend/src/routes/movie/[id]/+page.svelte
  frontend/src/routes/movie/[id]/+page.ts
  frontend/src/routes/person/[id]/+page.svelte
  frontend/src/routes/person/[id]/+page.ts
  frontend/src/routes/tv/[id]/+page.svelte
  frontend/src/routes/tv/[id]/+page.ts
  frontend/tests/movie.spec.ts
  frontend/tsconfig.json
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:, maintenance :safety_vest:

#314 feat: only show media with providers when no input
  frontend/src/routes/+page.svelte
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#316 Prefetch details, FAQ and About Us-pages
  frontend/src/lib/components/details/person.svelte
  frontend/src/lib/components/details/person_media.svelte
  frontend/src/lib/components/details/recommendations.svelte
  frontend/src/lib/components/media_search.svelte
  frontend/src/lib/components/navbar/navbar.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
Labels: enhancement :unicorn:

#322 chore: reduce size of favicon + branded named logo
  frontend/src/lib/components/navbar/navbar.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
  frontend/static/favicon.png
  frontend/static/navbar_logo_with_image.png
Labels: -prio:3 :zzz:, maintenance :safety_vest:

#315 refactor: change index to use load() + some cleaning up
  frontend/src/routes/+page.svelte
  frontend/src/routes/+page.ts
  frontend/tests/index.spec.ts
Labels: -prio:2 :construction_worker_man:, maintenance :safety_vest:

#324 fix: sidescroll on thin phones
  frontend/src/routes/+page.svelte
Labels: bug :bug:

#326 fix: ssr fetch breaking dev
  frontend/src/routes/+page.ts
  frontend/src/routes/movie/[id]/+page.ts
  frontend/src/routes/person/[id]/+page.ts
  frontend/src/routes/tv/[id]/+page.ts
Labels: bug :bug:

#321 feat!: up python to version 3.11, add dependabot and update dependencies
  .github/dependabot.yml
  backend/Dockerfile
  backend/poetry.lock
  backend/pyproject.toml
Labels: enhancement :unicorn:, -prio:3 :zzz:

#329 feat: add better colours and dynamic borders
  frontend/src/lib/components/country_selector.svelte
  frontend/src/lib/components/details/person.svelte
  frontend/src/lib/components/details/recommendations.svelte
  frontend/src/lib/components/details/seasons.svelte
  frontend/src/lib/components/details/top_card.svelte
  frontend/src/lib/components/footer.svelte
  frontend/src/lib/components/media_search.svelte
  frontend/src/lib/variables.js
  frontend/src/routes/+page.svelte
  frontend/tailwind.config.cjs
Labels: enhancement :unicorn:, maintenance :safety_vest:

#331 fix: inconsistency in SSR toggle
  frontend/src/routes/+page.ts
  frontend/src/routes/movie/[id]/+page.ts
  frontend/src/routes/person/[id]/+page.ts
  frontend/src/routes/tv/[id]/+page.ts
Labels: bug :bug:

#332 chore: add hot reloading and cleanup dockerfile
  docker-compose.yml
  frontend/Dockerfile
  frontend/node_svelte.config.js
  frontend/svelte.config.js
Labels: maintenance :safety_vest:

#333 refactor: move traefik middleware to .env
  docker-compose.yml
Labels: maintenance :safety_vest:

#261 Add release_date sort
  backend/app/db/search.py
  backend/app/routers/search.py
  backend/tests/test_sort.py
  frontend/src/lib/components/filters.svelte
  frontend/src/lib/components/media_search.svelte
  frontend/src/lib/components/no_results.svelte
  frontend/src/lib/stores/filters.js
  frontend/src/lib/stores/sorting.js
  frontend/src/routes/+page.svelte
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#272 feat!: change meilisearch to use nested providers
  backend/app/db/database_service.py
  backend/app/db/search.py
  backend/app/main.py
  backend/app/routers/search.py
  backend/app/schemas.py
  backend/cli.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/conftest.py
  backend/tests/test_filters.py
  backend/tests/test_media.py
  docker-compose.yml
  frontend/src/lib/components/media_search.svelte
  frontend/src/routes/+page.svelte
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#350 fix: make sure we index meilisearch in prod 🙈
  backend/cli.py
Labels: bug :bug:, -prio:1 :warning:

#348 feat: add Cache-Control max-age to /image
  backend/app/main.py
  backend/app/routers/image.py
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#353 feat: Add new meta description and make title more flexible
  frontend/src/lib/components/head.svelte
  frontend/src/routes/+page.svelte
Labels: -prio:3 :zzz:

#357 fix: Removed reset of providers on changing country
  frontend/src/lib/stores/providers.js
  frontend/src/lib/stores/providers.ts
  frontend/src/routes/+page.svelte
Labels: bug :bug:, -prio:2 :construction_worker_man:

#361 fix: multiselect is uwing wront itemcolor
  frontend/src/routes/+page.svelte
Labels: -prio:1 :warning:

#366 refactor: move metric services to its own docker-compose stack
  docker-compose.yml
  metrics/docker-compose.yml
  metrics/prometheus.yml
Labels: -prio:3 :zzz:, maintenance :safety_vest:

#363 feat: add a color for + images avatar
  frontend/src/lib/components/media_search.svelte
Labels: -prio:3 :zzz:

#365 chore: cleanup unused python models + remove db image
  backend/app/api.py
  backend/app/db/database_service.py
  backend/app/models.py
  backend/app/routers/media.py
  backend/app/routers/movie.py
  backend/app/routers/person.py
  backend/app/routers/providers.py
  backend/app/routers/tv.py
  backend/poetry.lock
  backend/pyproject.toml
  docker-compose.yml
  go_backend/Dockerfile
  internal/Dockerfile
Labels: -prio:3 :zzz:, maintenance :safety_vest:

#371 fix: up meilisearch to fix duplicate documents
  .gitignore
  docker-compose.yml
Labels: bug :bug:, -prio:1 :warning:
