Repository streamchaser/streamchaser, pull requests merged in 2022-02, with the labels that each got.

#140 Up MeiliSearch version to 0.25.2 - M1 support
  docker-compose.yml
Labels: enhancement :unicorn:, prio:medium :construction_worker_man:

#144 Add poetry
  backend/Dockerfile
  backend/poetry.lock
  backend/pyproject.toml
  backend/requirements.txt
Labels: enhancement :unicorn:, prio:low :zzz:

#146 Add Hot Module Replacement to frontend
  .gitignore
  docker-compose.yml
  frontend/Dockerfile
  frontend/svelte.config.js
Labels: enhancement :unicorn:, prio:low :zzz:

#143 Change pre-commit auto update schedule to monthly
  .pre-commit-config.yaml
Labels: prio:low :zzz:, maintenance :safety_vest:

#135 Move repeating frontend code into __layout
  frontend/src/components/error.svelte
  frontend/src/components/footer.svelte
  frontend/src/components/loading/spinner.svelte
  frontend/src/components/no_results.svelte
  frontend/src/routes/__error.svelte
  frontend/src/routes/__layout.svelte
  frontend/src/routes/about.svelte
  frontend/src/routes/faq.svelte
  frontend/src/routes/index.svelte
  frontend/src/routes/movie/[id].svelte
  frontend/src/routes/person/[id].svelte
  frontend/src/routes/tv/[id].svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#141 Add TV for the media cards that are TV on index page
  frontend/src/components/media_search.svelte
Labels: enhancement :unicorn:

#138 Add transitions to cookie disclaimer
  frontend/src/components/cookie_disclaimer.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#151 Remove unncessary entrypoints
  docker-compose.yml
Labels: prio:low :zzz:, maintenance :safety_vest:

#152 Implement multistage dockerfile for the backend
  .env
  .github/workflows/main.yml
  .gitignore
  .pre-commit-config.yaml
  backend/Dockerfile
  backend/app/config.py
  backend/app/main.py
  backend/app/routers/providers.py
  backend/cli.py
  backend/poetry.lock
  backend/pyproject.toml
  docker-compose.yml
  frontend/package-lock.json
Labels: enhancement :unicorn:, prio:low :zzz:

#154 Fixed alignment of page content
  frontend/src/routes/__layout.svelte
Labels: bug :bug:

#130 Adjust colors for higher contrast element contrast across themes
  frontend/src/components/details/person.svelte
  frontend/src/components/details/recommendations.svelte
  frontend/src/components/details/seasons.svelte
  frontend/src/components/media_search.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#161 Fix providers_X.txt path
  backend/app/db/database_service.py
Labels: bug :bug:, prio:high :warning:

#159 Implement httpx and await movie, person and tv requests
  backend/app/api.py
  backend/app/routers/movie.py
  backend/app/routers/tv.py
  backend/app/schemas.py
  backend/poetry.lock
  backend/pyproject.toml
Labels: enhancement :unicorn:, prio:medium :construction_worker_man:

#164 Change prettier arrowParens to avoid
  .pre-commit-config.yaml
  .prettierrc
  frontend/src/components/details/seasons.svelte
  frontend/src/components/details/top_card.svelte
  frontend/src/routes/index.svelte
  frontend/src/utils.ts
Labels: prio:low :zzz:, maintenance :safety_vest:

#160 Implement new select for filtering media based on genres or providers
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/no_results.svelte
  frontend/src/routes/index.svelte
Labels: enhancement :unicorn:, prio:high :warning:

#115 Add free providers
  .gitignore
  .pre-commit-config.yaml
  backend/app/api.py
  backend/app/api_helpers.py
  backend/app/db/crud.py
  backend/app/db/database_service.py
  backend/app/db/models.py
  backend/app/db/search.py
  backend/app/routers/providers.py
  backend/app/routers/search.py
  backend/app/schemas.py
  backend/app/util.py
  frontend/src/components/details/top_card.svelte
  frontend/src/components/media_search.svelte
  frontend/src/routes/index.svelte
  frontend/src/routes/movie/[id].svelte
  frontend/src/routes/tv/[id].svelte
  frontend/src/utils.ts
Labels: enhancement :unicorn:, prio:low :zzz:

#116 Add more supported countries
  backend/app/config.py
  frontend/src/components/navbar.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#158 Add interfaces + Clean weird typing/errors
  frontend/package.json
  frontend/src/components/cookie_disclaimer.svelte
  frontend/src/components/details/person.svelte
  frontend/src/components/details/read_more.svelte
  frontend/src/components/details/recommendations.svelte
  frontend/src/components/media_search.svelte
  frontend/src/components/no_results.svelte
  frontend/src/routes/index.svelte
  frontend/src/routes/tv/[id].svelte
  frontend/src/types.ts
  frontend/src/utils.ts
Labels: prio:medium :construction_worker_man:, maintenance :safety_vest:

#168 Switch from npm to yarn
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/yarn.lock
Labels: enhancement :unicorn:, prio:low :zzz:

#171 Fix CodeFactor issues
  backend/app/api_helpers.py
  backend/app/routers/search.py
  backend/app/schemas.py
  frontend/yarn.lock
Labels: prio:low :zzz:, maintenance :safety_vest:
