Repository streamchaser/streamchaser, pull requests merged in 2022-05, with the labels that each got.

#220 Remove duplicate update_index() call in full_setup()
  backend/cli.py
Labels: bug :bug:, -prio:1 :warning:

#217 Add CLI to interface with new internal Go API
  backend/app/api.py
  backend/app/util.py
  backend/cli.py
Labels: enhancement :unicorn:, -prio:3 :zzz:

#225 Fix broken genre badge redirects plus sort genres
  backend/app/db/database_service.py
  frontend/src/components/details/top_card.svelte
Labels: bug :bug:, -prio:1 :warning:

#219 Added initial E2E-tests for index and movie-detail routes + new CI-step for E2E
  .github/workflows/e2e.yml
  frontend/package.json
  frontend/playwright.config.ts
  frontend/tests/index.spec.ts
  frontend/tests/movie.spec.ts
  frontend/tests/request_mocks.ts
  frontend/tests/test_data/genres.json
  frontend/tests/test_data/harry_p_hits.json
  frontend/tests/test_data/m674_moviedetail.json
  frontend/tests/test_data/no_input_hits.json
  frontend/tests/test_data/providers.json
  frontend/yarn.lock
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#231 Fix SvelteKit breaking namechange + build as prod in CI
  .github/workflows/main.yml
  frontend/package.json
  frontend/src/app.html
  frontend/yarn.lock
Labels: bug :bug:, -prio:1 :warning:
