Repository streamchaser/streamchaser, pull requests merged in 2022-12, with the labels that each got.

#382 feat: add media card component with types
  backend/app/models.py
  backend/app/routers/search.py
  frontend/src/lib/components/details/top_card.svelte
  frontend/src/lib/components/media_card.svelte
  frontend/src/lib/components/media_search.svelte
  frontend/src/lib/generated/index.ts
  frontend/src/lib/generated/models/Hit.ts
  frontend/src/lib/generated/models/Meilisearch.ts
  frontend/src/lib/generated/models/Provider.ts
  frontend/src/lib/generated/models/Providers.ts
  frontend/src/lib/utils.ts
Labels: -prio:2 :construction_worker_man:

#384 feat: add providers for details
  backend/app/routers/media.py
  frontend/src/lib/components/details/person_media.svelte
  frontend/src/lib/components/details/recommendations.svelte
  frontend/src/lib/components/loading/spinner.svelte
  frontend/src/lib/components/media_card.svelte
  frontend/src/lib/types.ts
  frontend/src/lib/utils.ts
  frontend/src/routes/+page.svelte
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#369 feat: improve search for media containing & in titles
  backend/app/db/search.py
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#387 refactor: replaced svelte-persistent-store with svelte-store
  frontend/package.json
  frontend/src/lib/components/cookie_disclaimer.svelte
  frontend/src/lib/components/country_locator.svelte
  frontend/src/lib/components/country_selector.svelte
  frontend/src/lib/components/details/person_media.svelte
  frontend/src/lib/components/details/recommendations.svelte
  frontend/src/lib/components/details/top_card.svelte
  frontend/src/lib/components/filters.svelte
  frontend/src/lib/components/media_card.svelte
  frontend/src/lib/components/no_results.svelte
  frontend/src/lib/components/theme_selector.svelte
  frontend/src/lib/stores/cookie_disclaimer.js
  frontend/src/lib/stores/cookies.ts
  frontend/src/lib/stores/country.js
  frontend/src/lib/stores/filters.js
  frontend/src/lib/stores/genres.js
  frontend/src/lib/stores/input.js
  frontend/src/lib/stores/preferences.ts
  frontend/src/lib/stores/providers.ts
  frontend/src/lib/stores/sorting.js
  frontend/src/lib/stores/theme.js
  frontend/src/routes/+page.svelte
  frontend/src/routes/+page.ts
  frontend/src/routes/movie/[id]/+page.svelte
  frontend/src/routes/movie/[id]/+page.ts
  frontend/src/routes/tv/[id]/+page.svelte
  frontend/src/routes/tv/[id]/+page.ts
  frontend/yarn.lock
Labels: -prio:3 :zzz:, maintenance :safety_vest:

#391 fix: 301 on genres by removing trailing /
  frontend/src/routes/+page.ts
Labels: bug :bug:, -prio:1 :warning:

#393 fix: missing quotation marks on stores of type string
  frontend/src/lib/stores/preferences.ts
Labels: bug :bug:, -prio:1 :warning:

#392 feat: add swagger to internal + update go module names
  .gitignore
  go_backend/go.mod
  go_backend/go.sum
  go_backend/main.go
  internal/Dockerfile
  internal/go.mod
  internal/go.sum
  internal/main.go
  internal/routes.go
Labels: documentation :books:, enhancement :unicorn:, -prio:3 :zzz:

#396 fix: fix current country store breaking
  frontend/src/lib/stores/preferences.ts
  frontend/src/lib/utils.ts
Labels: bug :bug:, -prio:1 :warning:

#398 feat: add meilisearch stats endpoint
  backend/app/main.py
  backend/app/routers/stats.py
Labels: enhancement :unicorn:, -prio:3 :zzz:

#400 chore: 10x the amount of connections to TMDB
  internal/routes.go
Labels: -prio:3 :zzz:, maintenance :safety_vest:

#397 feat: add updated at timestamp to meilisearch documents
  backend/app/db/search.py
  internal/types.go
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#402 chore: sort over exactness in ranking rule priority
  backend/app/db/search.py
Labels: -prio:2 :construction_worker_man:, maintenance :safety_vest:

#401 refactor: zero debounce = better experience?
  frontend/src/routes/+page.svelte
Labels: -prio:3 :zzz:, maintenance :safety_vest:

#399 feat: add command to remove stale media
  backend/app/db/database_service.py
  backend/cli.py
  backend/poetry.lock
  backend/pyproject.toml
  docker-compose.yml
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:, maintenance :safety_vest:

#395 feat: use the new 251 countries
  backend/app/config.py
  backend/app/db/database_service.py
  backend/app/routers/country.py
  backend/cli.py
  frontend/package.json
  frontend/src/lib/components/country_locator.svelte
  frontend/src/lib/components/country_selector.svelte
  frontend/src/lib/components/navbar/navbar.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
  frontend/src/lib/generated/go/index.ts
  frontend/src/lib/generated/go/models/main_Country.ts
  frontend/src/lib/generated/go/models/main_Genre.ts
  frontend/src/lib/generated/index.ts
  frontend/src/lib/generated/models/Media.ts
  frontend/src/lib/variables.js
  frontend/src/routes/+layout.svelte
  frontend/src/routes/+layout.ts
  frontend/tests/index.spec.ts
  go_backend/routes.go
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#407 fix: e2e tests with new page/layout load + upgrade playwright to newest version
  backend/app/routers/country.py
  backend/app/routers/genres.py
  backend/app/routers/stats.py
  frontend/package.json
  frontend/src/routes/+page.ts
  frontend/src/routes/movie/[id]/+page.ts
  frontend/src/routes/person/[id]/+page.ts
  frontend/src/routes/tv/[id]/+page.ts
  frontend/tests/index.spec.ts
  frontend/tests/movie.spec.ts
  frontend/tests/request_mocks.ts
  frontend/tests/test_data/countries.json
  frontend/tests/test_data/harry_p_hits.json
  frontend/tests/test_data/m674_moviedetail.json
  frontend/tests/test_data/no_input_hits.json
  frontend/tests/test_data/providers.json
  frontend/yarn.lock
Labels: bug :bug:, -prio:2 :construction_worker_man:

#405 feat: add sitemap that is generated from meilisearch data
  .gitignore
  backend/cli.py
Labels: -prio:1 :warning:

#413 fix: unpredictable country selector size
  frontend/src/lib/components/country_selector.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
Labels: bug :bug:

#411 feat: setup svelte check and fix errors warning and hints 🧹
  .github/workflows/svelte-check.yml
  frontend/package.json
  frontend/src/global.d.ts
  frontend/src/lib/components/collapse.svelte
  frontend/src/lib/components/cookie_disclaimer.svelte
  frontend/src/lib/components/details/recommendations.svelte
  frontend/src/lib/components/details/seasons.svelte
  frontend/src/lib/components/details/top_card.svelte
  frontend/src/lib/components/error.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
  frontend/src/lib/components/theme_selector.svelte
  frontend/src/lib/stores/preferences.ts
  frontend/src/routes/+page.svelte
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: -prio:2 :construction_worker_man:, maintenance :safety_vest:

#388 feat: add go fmt pre-commit
  .pre-commit-config.yaml
  internal/routes.go
Labels: enhancement :unicorn:, -prio:3 :zzz:, maintenance :safety_vest:

#390 feat: change cookiedisclaimer to include options for cookies
  frontend/src/app.html
  frontend/src/lib/components/cookie_disclaimer.svelte
  frontend/src/lib/components/country_locator.svelte
  frontend/src/lib/components/details/recommendations.svelte
  frontend/src/lib/cookies.ts
  frontend/src/lib/stores/cookies.ts
  frontend/src/lib/stores/preferences.ts
  frontend/src/lib/utils.ts
  frontend/src/routes/+layout.svelte
  frontend/src/routes/movie/[id]/+page.svelte
  frontend/src/routes/tv/[id]/+page.svelte
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#414 fix: cookies are properly stored in localstorage
  frontend/src/lib/stores/cookies.ts
  frontend/src/routes/+layout.svelte
Labels: bug :bug:, -prio:1 :warning:

#416 fix: country http redirect from trailing slash
  backend/Dockerfile
  frontend/src/lib/components/country_locator.svelte
Labels: bug :bug:, -prio:1 :warning:
