Repository streamchaser/streamchaser, pull requests merged in 2022-07, with the labels that each got.

#155 Credit JustWatch for data
  frontend/src/components/footer.svelte
  frontend/static/tmdb.svg
Labels: enhancement :unicorn:, -prio:1 :warning:

#244 Add new logos + dynamic navbar
  frontend/src/components/country_selector.svelte
  frontend/src/components/footer.svelte
  frontend/src/components/navbar.svelte
  frontend/src/components/navbar/navbar.svelte
  frontend/src/components/navbar/phone_navbar.svelte
  frontend/src/components/theme_selector.svelte
  frontend/src/routes/__layout.svelte
  frontend/static/favicon.png
  frontend/static/logo_with_text_and_image.png
  frontend/static/navbar_logo_with_image.png
Labels: enhancement :unicorn:, -prio:1 :warning:

#246 General frontend cleanups
  frontend/src/components/details/read_more.svelte
  frontend/src/components/details/recommendations.svelte
  frontend/src/components/details/seasons.svelte
  frontend/src/components/details/top_card.svelte
  frontend/src/components/no_results.svelte
  frontend/src/routes/index.svelte
Labels: bug :bug:, maintenance :safety_vest:

#250 Add imdb for person & TV
  backend/app/api.py
  backend/app/schemas.py
  frontend/src/components/details/top_card.svelte
  frontend/src/routes/person/[id].svelte
  frontend/src/routes/tv/[id].svelte
Labels: enhancement :unicorn:

#254 Up required Python version to 3.10 - match cases bby!
  .pre-commit-config.yaml
  backend/pyproject.toml
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#226 Fix broken CORS on go_backend for vercel urls
  go_backend/main.go
Labels: bug :bug:, -prio:2 :construction_worker_man:

#257 Add filtering of media types
  backend/app/config.py
  backend/app/db/database_service.py
  backend/app/db/search.py
  backend/app/routers/search.py
  backend/app/schemas.py
  backend/tests/conftest.py
  backend/tests/test_filters.py
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#256 Update outdated information and add new graphics to README
  README.md
  static/logo-slogan-hori-b.svg
  static/logo-slogan-hori-w.svg
  static/logo-slogan-verti.png
  static/streamchaser-tech-stack.png
Labels: documentation :books:, -prio:2 :construction_worker_man:

#259 Frontend for movie & TV filtering
  frontend/src/components/filters.svelte
  frontend/src/components/no_results.svelte
  frontend/src/routes/index.svelte
  frontend/src/stores/filters.js
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#263 Add filter for empty providers + tests
  backend/app/routers/search.py
  backend/tests/test_filters.py
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#265 Buttons to close on click
  frontend/src/components/filters.svelte
  frontend/src/components/footer.svelte
  frontend/src/components/navbar/navbar.svelte
  frontend/src/components/navbar/phone_navbar.svelte
  frontend/src/components/theme_selector.svelte
  frontend/static/GitHub-Mark-120px-plus.png
  frontend/static/GitHub-Mark-Light-120px-plus.png
Labels: enhancement :unicorn:

#267 Add frontend for no providers filtering
  frontend/src/components/filters.svelte
  frontend/src/components/navbar/navbar.svelte
  frontend/src/components/no_results.svelte
  frontend/src/routes/index.svelte
  frontend/src/stores/filters.js
Labels: enhancement :unicorn:

#258 Change media endpoint to lookup IDs from MeiliSearch
  .github/workflows/e2e.yml
  .github/workflows/main.yml
  backend/app/db/search.py
  backend/app/routers/media.py
  backend/tests/test_api.py
  backend/tests/test_media.py
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#253 Add country ip lookup route and component
  backend/app/config.py
  backend/app/main.py
  backend/app/routers/country.py
  backend/poetry.lock
  backend/pyproject.toml
  docker-compose.yml
  frontend/src/components/country_locator.svelte
  frontend/src/routes/__layout.svelte
  frontend/src/stores/country.js
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:
