Repository streamchaser/streamchaser, pull requests merged in 2022-01, with the labels that each got.

#112 Clickable genres in details view
  frontend/src/components/details/top_card.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#113 Update readme
  README.md
Labels: documentation :books:

#121 Full-setup not fetching newest json.gz files from tmdb
  backend/app/api.py
Labels: bug :bug:, prio:high :warning:

#122 Support for opening new tabs with ctrl/mid mouse/shift
  frontend/src/components/details/person.svelte
  frontend/src/components/details/person_media.svelte
  frontend/src/components/details/recommendations.svelte
  frontend/src/components/media_search.svelte
  frontend/src/utils.ts
Labels: enhancement :unicorn:, prio:low :zzz:

#93 More info on card in detailsview
  frontend/src/components/details/top_card.svelte
  frontend/src/routes/movie/[id].svelte
  frontend/src/routes/person/[id].svelte
  frontend/src/routes/tv/[id].svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#118 Meilisearch unable to index because of too large payload
  backend/app/cli.py
  backend/app/db/database_service.py
Labels: bug :bug:, prio:high :warning:

#120 Better handling of media with no poster path
  frontend/src/components/details/top_card.svelte
  frontend/src/components/media_search.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#123 Frontend overhaul
  frontend/src/app.html
  frontend/src/components/details/person.svelte
  frontend/src/components/details/person_media.svelte
  frontend/src/components/details/recommendations.svelte
  frontend/src/components/details/seasons.svelte
  frontend/src/components/details/top_card.svelte
  frontend/src/components/error.svelte
  frontend/src/components/loading/spinner.svelte
  frontend/src/components/media_search.svelte
  frontend/src/routes/index.svelte
Labels: enhancement :unicorn:

#42 pre-commit black --all-files
  .pre-commit-config.yaml
  backend/app/api.py
  backend/app/api_helpers.py
  backend/app/cli.py
  backend/app/db/crud.py
  backend/app/db/database.py
  backend/app/db/database_service.py
  backend/app/db/models.py
  backend/app/db/search.py
  backend/app/util.py
  backend/tests/test_api.py
Labels: enhancement :unicorn:, prio:medium :construction_worker_man:

#43 Prettier added to pre-commit + run --all-files
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .pre-commit-config.yaml
  .prettierrc
  README.md
  docker-compose.yml
  frontend/jsconfig.json
  frontend/src/app.html
  frontend/src/components/avatar.svelte
  frontend/src/components/collapse.svelte
  frontend/src/components/cookie_disclaimer.svelte
  frontend/src/components/details/person.svelte
  frontend/src/components/details/person_media.svelte
  frontend/src/components/details/read_more.svelte
  frontend/src/components/details/recommendations.svelte
  frontend/src/components/details/seasons.svelte
  frontend/src/components/details/top_card.svelte
  frontend/src/components/error.svelte
  frontend/src/components/footer.svelte
  frontend/src/components/loading/spinner.svelte
  frontend/src/components/media_search.svelte
  frontend/src/components/navbar.svelte
  frontend/src/components/no_results.svelte
  frontend/src/routes/__error.svelte
  frontend/src/routes/about.svelte
  frontend/src/routes/faq.svelte
  frontend/src/routes/index.svelte
  frontend/src/routes/movie/[id].svelte
  frontend/src/routes/person/[id].svelte
  frontend/src/routes/tv/[id].svelte
  frontend/src/stores/cookie_disclaimer.js
  frontend/src/stores/country.js
  frontend/src/stores/genres.js
  frontend/src/stores/input.js
  frontend/src/stores/providers.js
  frontend/src/utils.ts
  frontend/src/variables.js
  frontend/svelte.config.js
  frontend/tsconfig.json
Labels: enhancement :unicorn:, prio:medium :construction_worker_man:

#127 Support for themes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app.html
  frontend/src/components/cookie_disclaimer.svelte
  frontend/src/components/details/person.svelte
  frontend/src/components/details/seasons.svelte
  frontend/src/components/details/top_card.svelte
  frontend/src/components/footer.svelte
  frontend/src/components/media_search.svelte
  frontend/src/components/navbar.svelte
  frontend/src/routes/index.svelte
  frontend/src/stores/theme.js
  frontend/static/GitHub-Mark-120px-plus.png
  frontend/static/GitHub-Mark-Light-120px-plus.png
  frontend/static/github.svg
Labels: enhancement :unicorn:

#129 Change color of spinner to match themes
  frontend/src/components/loading/spinner.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#131 Stop use of CDN in frontend
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.cjs
  frontend/src/app.css
  frontend/src/app.html
  frontend/src/routes/__layout.svelte
  frontend/tailwind.config.cjs
Labels: enhancement :unicorn:, prio:low :zzz:

#136 Make top cards follow themes
  frontend/src/components/details/top_card.svelte
Labels: enhancement :unicorn:

#132 Go to top button
  frontend/src/components/back_to_top_button.svelte
  frontend/src/routes/index.svelte
Labels: enhancement :unicorn:, prio:low :zzz:

#134 Implement multistage Dockerfiles
  .env
  .gitignore
  docker-compose.yml
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/svelte.config.js
Labels: enhancement :unicorn:, prio:medium :construction_worker_man:
