Repository streamchaser/streamchaser, pull requests merged in 2023-01, with the labels that each got.

#423 chore: clean-up pre-commit mess
  go_backend/routes.go
  internal/routes.go
Labels: maintenance :safety_vest:

#422 chore: up meilisearch version to newest
  docker-compose.yml
Labels: -prio:2 :construction_worker_man:, maintenance :safety_vest:

#425 bug: fix providers on breaking bad(probably more) by removing translation
  internal/routes.go
Labels: bug :bug:, -prio:1 :warning:

#427 chore: update tech credits
  README.md
Labels: documentation :books:, -prio:3 :zzz:

#429 fix: change faulty environment
  .github/workflows/e2e.yml
  docker-compose.yml
Labels: bug :bug:, -prio:1 :warning:

#431 fix: shorten cache max-age
  backend/app/routers/image.py
Labels: bug :bug:, -prio:1 :warning:

#430 feat: add imdb ratings
  .gitignore
  backend/app/db/search.py
  backend/app/models.py
  backend/app/routers/media.py
  backend/app/routers/search.py
  backend/cli.py
  backend/tests/conftest.py
  backend/tests/test_filters.py
  backend/tests/test_sort.py
  frontend/src/lib/components/details/top_card.svelte
  frontend/src/lib/components/filters.svelte
  frontend/src/lib/components/media_card.svelte
  frontend/src/lib/components/no_results.svelte
  frontend/src/lib/generated/models/Hit.ts
  frontend/src/lib/stores/preferences.ts
  frontend/src/lib/utils.ts
  frontend/src/routes/+page.svelte
  frontend/src/routes/movie/[id]/+page.svelte
  frontend/src/routes/person/[id]/+page.svelte
  frontend/src/routes/tv/[id]/+page.svelte
  internal/routes.go
  internal/types.go
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:
