Repository streamchaser/streamchaser, pull requests merged in 2023-04, with the labels that each got.

#460 chore: remove dead old code
  backend/app/api.py
  backend/app/api_helpers.py
Labels: -prio:3 :zzz:, maintenance :safety_vest:

#464 fix: broken dependabot
  .github/dependabot.yml
Labels: bug :bug:, -prio:3 :zzz:, maintenance :safety_vest:

#475 chore: change to vite preprocess and remove rollup
  frontend/package.json
  frontend/svelte.config.js
  frontend/yarn.lock
Labels: maintenance :safety_vest:, dependencies

#476 chore: remove svelte-preprocess (we use vite's now)
  frontend/package.json
  frontend/yarn.lock
Labels: maintenance :safety_vest:, dependencies

#484 refactor!: bump and fix svelte-check changes
  .github/workflows/svelte-check.yml
  backend/app/api.py
  backend/app/models.py
  frontend/package.json
  frontend/src/lib/components/details/person.svelte
  frontend/src/lib/components/details/top_card.svelte
  frontend/src/lib/components/media_card.svelte
  frontend/src/lib/components/media_search.svelte
  frontend/src/lib/components/navbar/navbar.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
  frontend/src/lib/generated/index.ts
  frontend/src/lib/generated/models/Genre.ts
  frontend/src/lib/generated/models/Movie.ts
  frontend/src/lib/generated/models/SelectCountryProvidersResultProvidersItem.ts
  frontend/src/lib/generated/models/SelectUserCustomListsResult.ts
  frontend/src/lib/generated/models/SelectUserCustomListsResultCustomListsItem.ts
  frontend/src/lib/generated/models/SelectUserCustomListsResultCustomListsItemMediaItem.ts
  frontend/src/lib/generated/models/SelectUserFavoritesResult.ts
  frontend/src/lib/generated/models/SelectUserWatchListResult.ts
  frontend/src/lib/generated/models/SelectUserWatchListResultWatchListItem.ts
  frontend/src/lib/generated/models/TV.ts
  frontend/src/lib/generated/models/UpdateCustomListAddResult.ts
  frontend/src/lib/stores/preferences.ts
  frontend/src/lib/types.ts
  frontend/src/lib/utils.ts
  frontend/yarn.lock
  internal/go.mod
  internal/go.sum
Labels: -prio:3 :zzz:, maintenance :safety_vest:, javascript
