Repository streamchaser/streamchaser, pull requests merged in 2023-05, with the labels that each got.

#496 fix: slow down our internal job to deal with the TMDB 429 :(
  backend/cli.py
  internal/routes.go
  internal/types.go
Labels: bug :bug:, -prio:1 :warning:

#504 feat: add formatted logging to file for internal
  .gitignore
  internal/main.go
  internal/routes.go
Labels: enhancement :unicorn:, -prio:3 :zzz:

#506 feat: even more dynamic tqdm pbar for update_media!
  backend/cli.py
  internal/routes.go
Labels: enhancement :unicorn:, -prio:3 :zzz:, maintenance :safety_vest:

#507 chore: update favicon
  frontend/static/favicon.png
Labels: -prio:3 :zzz:, maintenance :safety_vest:

#505 fix: handle providers being empty sometimes
  backend/app/db/database_service.py
Labels: bug :bug:, -prio:2 :construction_worker_man:

#512 chore: up playwright dependencies and switch experimental
  frontend/package.json
  frontend/yarn.lock
Labels: maintenance :safety_vest:

#462 feat: add HTTP exception for handling of auth errors in backend
  backend/app/util.py
Labels: enhancement :unicorn:

#532 feat: add initial logging for backend
  .gitignore
  backend/app/api.py
  backend/app/db/database_service.py
  backend/app/routers/country.py
  backend/app/util.py
  backend/cli.py
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:, maintenance :safety_vest:
