Repository streamchaser/streamchaser, pull requests merged in 2023-03, with the labels that each got.

#445 chore: remove unused checkboxes from PR template
  .github/pull_request_template.md
Labels: -prio:3 :zzz:, maintenance :safety_vest:

#444 chore: remove --platform Python hack
  .pre-commit-config.yaml
  backend/Dockerfile
Labels: -prio:2 :construction_worker_man:, maintenance :safety_vest:

#443 feat: add edgedb
  backend/app/api.py
  backend/app/db/database.py
  backend/app/db/database_service.py
  backend/app/db/queries/get_countries.edgeql
  backend/app/db/queries/get_countries_async_edgeql.py
  backend/app/db/queries/get_genres.edgeql
  backend/app/db/queries/get_genres_async_edgeql.py
  backend/app/db/queries/insert_countries.edgeql
  backend/app/db/queries/insert_countries_async_edgeql.py
  backend/app/db/queries/insert_genres.edgeql
  backend/app/db/queries/insert_genres_async_edgeql.py
  backend/app/main.py
  backend/app/routers/countries.py
  backend/app/routers/genres.py
  backend/app/routers/providers.py
  backend/app/routers/search.py
  backend/cli.py
  backend/poetry.lock
  backend/pyproject.toml
  dbschema/default.esdl
  dbschema/futures.esdl
  dbschema/migrations/00001.edgeql
  docker-compose.yml
  edgedb.toml
  justfile
Labels: enhancement :unicorn:, -prio:1 :warning:

#441 Add people to meilisearch media, and therefore searchable
  backend/app/api.py
  backend/app/db/database_service.py
  backend/cli.py
  frontend/src/lib/components/filters.svelte
  frontend/src/lib/components/media_card.svelte
  frontend/src/lib/components/no_results.svelte
  frontend/src/lib/stores/preferences.ts
  frontend/src/routes/+page.svelte
  internal/main.go
  internal/routes.go
  internal/types.go
  justfile
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#452 feat: add QoL access to cli.py with 'just cli <command>'
  justfile
Labels: enhancement :unicorn:, -prio:3 :zzz:

#450 chore: remove go_backend
  .github/workflows/e2e.yml
  .github/workflows/svelte-check.yml
  .gitignore
  README.md
  backend/app/db/database_service.py
  backend/cli.py
  backend/tests/test_cache.py
  docker-compose.yml
  frontend/package.json
  frontend/src/lib/components/country_selector.svelte
  frontend/src/lib/components/media_search.svelte
  frontend/src/lib/components/navbar/navbar.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
  frontend/src/lib/generated/go/index.ts
  frontend/src/lib/generated/go/models/main_Country.ts
  frontend/src/lib/generated/go/models/main_Genre.ts
  frontend/src/lib/generated/index.ts
  frontend/src/lib/generated/models/ClientStats.ts
  frontend/src/lib/generated/models/Genre.ts
  frontend/src/lib/generated/models/GetCountriesResult.ts
  frontend/src/lib/generated/models/GetGenresResult.ts
  frontend/src/lib/generated/models/Hit.ts
  frontend/src/lib/generated/models/IndexStats.ts
  frontend/src/lib/variables.js
  frontend/src/routes/+layout.ts
  frontend/src/routes/+page.ts
  frontend/tests/movie.spec.ts
  frontend/tests/request_mocks.ts
  go_backend/Dockerfile
  go_backend/go.mod
  go_backend/go.sum
  go_backend/main.go
  go_backend/routes.go
Labels: maintenance :safety_vest:

#449 feat: add backend for users and watch lists
  .pre-commit-config.yaml
  backend/app/config.py
  backend/app/db/queries/generated.py
  backend/app/db/queries/get_countries_async_edgeql.py
  backend/app/db/queries/get_genres_async_edgeql.py
  backend/app/db/queries/insert_countries_async_edgeql.py
  backend/app/db/queries/insert_genres_async_edgeql.py
  backend/app/db/queries/insert_media.edgeql
  backend/app/db/queries/insert_user.edgeql
  backend/app/db/queries/select_countries.edgeql
  backend/app/db/queries/select_genres.edgeql
  backend/app/db/queries/select_user_watch_list.edgeql
  backend/app/db/queries/update_user_watch_list_add.edgeql
  backend/app/db/queries/update_user_watch_list_remove.edgeql
  backend/app/main.py
  backend/app/models.py
  backend/app/routers/countries.py
  backend/app/routers/genres.py
  backend/app/routers/user.py
  backend/app/routers/watch_list.py
  backend/app/util.py
  backend/cli.py
  backend/poetry.lock
  backend/pyproject.toml
  dbschema/default.esdl
  dbschema/migrations/00002.edgeql
  dbschema/migrations/00003.edgeql
  dbschema/migrations/00004.edgeql
  dbschema/migrations/00005.edgeql
  justfile
Labels: enhancement :unicorn:, -prio:1 :warning:

#451 Add providers and links with display priority sorting
  backend/app/db/database_service.py
  backend/app/db/queries/generated.py
  backend/app/db/queries/insert_providers.edgeql
  backend/app/db/queries/select_countries_with_providers.edgeql
  backend/app/db/queries/select_country_providers.edgeql
  backend/app/db/queries/update_country_providers.edgeql
  backend/app/routers/countries.py
  backend/app/routers/providers.py
  backend/cli.py
  dbschema/default.esdl
  dbschema/migrations/00001.edgeql
  dbschema/migrations/00002.edgeql
  dbschema/migrations/00003.edgeql
  dbschema/migrations/00004.edgeql
  dbschema/migrations/00005.edgeql
  frontend/src/lib/components/country_selector.svelte
  frontend/src/lib/components/media_search.svelte
  frontend/src/lib/components/navbar/navbar.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
  frontend/src/lib/generated/index.ts
  frontend/src/lib/generated/models/InsertUserResult.ts
  frontend/src/lib/generated/models/SelectCountriesResult.ts
  frontend/src/lib/generated/models/SelectCountryProvidersResult.ts
  frontend/src/lib/generated/models/SelectCountryProvidersResultProvidersItem.ts
  frontend/src/lib/generated/models/SelectGenresResult.ts
  frontend/src/lib/generated/models/SelectUserWatchListResult.ts
  frontend/src/lib/generated/models/SelectUserWatchListResultWatchListItem.ts
  frontend/src/routes/+layout.ts
  frontend/src/routes/+page.svelte
  frontend/src/routes/+page.ts
  frontend/tests/test_data/providers.json
  justfile
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#454 chore: up sveltekit, svelte and vite versions
  frontend/package.json
  frontend/svelte.config.js
  frontend/yarn.lock
Labels: -prio:2 :construction_worker_man:, maintenance :safety_vest:

#448 feat: initial setup of oauth for frontend
  frontend/src/lib/components/navbar/navbar.svelte
  frontend/src/lib/components/navbar/phone_navbar.svelte
  frontend/src/lib/components/sign_in/auth.svelte
  frontend/src/lib/stores/stores.ts
  frontend/src/lib/types.ts
  frontend/src/lib/utils.ts
  frontend/src/routes/+layout.ts
  frontend/src/routes/profile/+layout.svelte
  frontend/src/routes/profile/+page.svelte
  frontend/tsconfig.json
Labels: enhancement :unicorn:, -prio:2 :construction_worker_man:

#457 feat: add ruff to pre-commit
  .pre-commit-config.yaml
  backend/app/api.py
  backend/app/api_helpers.py
  backend/app/db/database.py
  backend/app/db/database_service.py
  backend/app/db/queries/generated.py
  backend/app/main.py
  backend/app/routers/countries.py
  backend/app/routers/country.py
  backend/app/routers/genres.py
  backend/app/routers/image.py
  backend/app/routers/media.py
  backend/app/routers/movie.py
  backend/app/routers/person.py
  backend/app/routers/providers.py
  backend/app/routers/search.py
  backend/app/routers/stats.py
  backend/app/routers/tv.py
  backend/app/routers/user.py
  backend/app/routers/watch_list.py
  backend/app/util.py
  backend/cli.py
  backend/tests/conftest.py
  backend/tests/test_filters.py
Labels: -prio:3 :zzz:, maintenance :safety_vest:
